### PR TITLE
Fix deprecation warnings in Newton

### PR DESCRIPTION
**Pull request by ramereth**
This removes (most) of the deprecation warnings I see in the log files. There's a few exceptions which include things that pull in the package provided config file. I'm going to assume this gets fixed upstream in later releases.

@osuosl-cookbooks/chefs I'd like to get this reviewed soon so that I can rebase this into my Ocata branch and apply fixes there as well.

### CODE REVIEW

**Comment by ramereth** [comment]
[Convert osl-openstack to support Ocata](https://trello.com/c/GC9GscBL/563-convert-osl-openstack-to-support-ocata)

**Comment by ramereth** [comment]
[Convert osl-openstack to support Ocata](https://trello.com/c/GC9GscBL/563-convert-osl-openstack-to-support-ocata)

**Comment by ramereth** [comment]
!bump minor openstack_newton

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v4.1.0.  Have a nice day!

**Pull request merged**
