### PR TITLE
Chef 13 fixes

### PR DESCRIPTION
**Pull request by ramereth**

### CODE REVIEW

**Comment by ramereth** [comment]
[Chef 13: osl-openstack](https://trello.com/c/bHF7gJU6/1010-chef-13-osl-openstack)

**Comment by ramereth** [comment]
@osuosl-cookbooks/chefs I believe this is finally ready for review.

A few notes:
- The following suites are known to fail and are OK to ignore: mellanox-neo, upgrade
- If a test fails, try converging again and re-running with verify

**Comment by TravisWhitehead** [comment]
@ramereth Have you encountered this error when running any of the suites? Converging multiple times doesn't help. From `default-centos-7` :

```
       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/mysql2_chef_gem/libraries/z_provider_mapping.rb
       ================================================================================
       
       NoMethodError
       -------------
       undefined method `set' for Chef::Platform:Class
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/mysql2_chef_gem/libraries/z_provider_mapping.rb:4:in `<top (required)>'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/mysql2_chef_gem/libraries/z_provider_mapping.rb:
       
         1:  #########
         2:  # mysql2_chef_gem
         3:  #########
         4>> Chef::Platform.set platform: :amazon, resource: :mysql2_chef_gem, provider: Chef::Provider::Mysql2ChefGem::Mysql
         5:  Chef::Platform.set platform: :centos, version: '< 7.0', resource: :mysql2_chef_gem, provider: Chef::Provider::Mysql2ChefGem::Mysql
         6:  Chef::Platform.set platform: :centos, version: '>= 7.0', resource: :mysql2_chef_gem, provider: Chef::Provider::Mysql2ChefGem::Mysql
         7:  Chef::Platform.set platform: :debian, resource: :mysql2_chef_gem, provider: Chef::Provider::Mysql2ChefGem::Mysql
         8:  Chef::Platform.set platform: :fedora, version: '< 19', resource: :mysql2_chef_gem, provider: Chef::Provider::Mysql2ChefGem::Mysql
         9:  Chef::Platform.set platform: :fedora, version: '>= 19', resource: :mysql2_chef_gem, provider: Chef::Provider::Mysql2ChefGem::Mysql
        10:  Chef::Platform.set platform: :omnios, resource: :mysql2_chef_gem, provider: Chef::Provider::Mysql2ChefGem::Mysql
        11:  Chef::Platform.set platform: :redhat, version: '< 7.0', resource: :mysql2_chef_gem, provider: Chef::Provider::Mysql2ChefGem::Mysql
        12:  Chef::Platform.set platform: :redhat, version: '>= 7.0', resource: :mysql2_chef_gem, provider: Chef::Provider::Mysql2ChefGem::Mysql
        13:  Chef::Platform.set platform: :scientific, version: '< 7.0', resource: :mysql2_chef_gem, provider: Chef::Provider::Mysql2ChefGem::Mysql
       
       System Info:
       ------------
       chef_version=13.8.5
       platform=centos
       platform_version=7.5.1804
       ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
       program_name=chef-client worker: ppid=1973;start=21:33:42;
       executable=/opt/chef/bin/chef-client
       
       
       Running handlers:
       [2018-10-30T21:33:50+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-10-30T21:33:50+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 07 seconds
       [2018-10-30T21:33:50+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-10-30T21:33:50+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-10-30T21:33:50+00:00] ERROR: undefined method `set' for Chef::Platform:Class
       [2018-10-30T21:33:50+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by TravisWhitehead** [comment]
@ramereth Is this ready for review now, or are there more fixes on the way?

**Comment by ramereth** [comment]
@TravisWhitehead ready for review

**Comment by TravisWhitehead** [comment]
The only other suite giving me problems is `controller-centos-7`. After converging/verifying multiple times, `neutron-linuxbridge-agent` service is still not running.

It may just be that the suite is finnicky?

**Comment by ramereth** [comment]
@TravisWhitehead my recent commits should resolve those issues. Thanks for noticing them!

**Comment by ramereth** [comment]
!bump major openstack_newton

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v4.0.0.  Have a nice day!

**Pull request merged**
