### PR TITLE
Nagios monitoring in Newton

### PR DESCRIPTION
**Pull request by ramereth**
This pulls in nagios plugins from the OpenStack project that are being
maintained and still work in Newton. The previous plugins we were using worked
in Mitaka, but don't appear to work in Newton. This isn't exactly the same
checks as we had but it should be good enough for what we need.

### CODE REVIEW

**Comment by eldebrim** [comment]
So i can't seem to able to converge mon-controller-centos-74 suite, but it appears unrelated to this PR
`       
       
       NoMethodError
       -------------
       undefined method `each' for nil:NilClass
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/osl-openstack/recipes/default.rb:319:in `from_file'
         /tmp/kitchen/cache/cookbooks/osl-openstack/recipes/mon.rb:30:in `from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/osl-openstack/recipes/default.rb:
       
       312:    only_if { node['kernel']['machine'] == 'ppc64le' }
       313:    action :add
       314:  end
       315:  
       316:  include_recipe 'base::packages'
       317:  include_recipe 'yum-epel'
       318:  
       319>> node['yum-epel']['repos'].each do |repo|
       320:    next unless node['yum'][repo]['managed']
       321:    r = resources(yum_repository: repo)
       322:    # If we already have excludes, include them and append zeromq
       323:    r.exclude = [r.exclude, 'zeromq*'].reject(&:nil?).join(' ')
       324:  end
       325:  
       326:  %w(
       327:    libffi-devel
       328:    openssl-devel
`

**Comment by ramereth** [comment]
@eldebrim rm Berksfile.lock and try again

**Comment by ramereth** [comment]
!bump patch openstack_newton

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v3.0.4.  Have a nice day!

**Pull request merged**
