### PR TITLE
Replace any occurrence of yum-centos/yum-epel/yum-elrepo with osl-repos equivalents

### PR DESCRIPTION
**Pull request by TheREK3R**

### CODE REVIEW

**Comment by ramereth** [comment]
LGTM

**Comment by ramereth** [comment]
LGTM

**Review by ramereth — APPROVED** [review]
Please do a minor bump on `openstack_stein`

**Comment by TheREK3R** [comment]
!bump minor openstack_stein

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v9.1.0.  Have a nice day!

**Pull request merged**
