### PR TITLE
Including ibm-power as a dependency

### PR DESCRIPTION
**Pull request by knightsamar**
To fix the `execute[ppc64_cpu_smt_off]`resource convergence failure on this cookbook.
`ibm-power` recipe does the thing described at http://wiki.osuosl.org/openpower/openstack.html#turn-off-smt

### CODE REVIEW

**Comment by ramereth** [comment]
@knightsamar can you please update the compute chefspec to test for the inclusion of this new recipe?

**Comment by knightsamar** [comment]
Will do

**Comment by knightsamar** [comment]
Fixed and rebased.

**Comment by knightsamar** [comment]
!bump patch openstack_mitaka

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v2.3.4.  Have a nice day!

**Pull request merged**
