### PR TITLE
Replace systemd resource with osl equivilent

### PR DESCRIPTION
**Pull request by TheREK3R**

### CODE REVIEW

**Comment by ramereth** [comment]
@TheREK3R for some reason the unit test is failing.

**Comment by TheREK3R** [comment]
Yeah I think I forgot to fox before pushing. I will do that tomorrow

**Review by ramereth — APPROVED** [review]

**Comment by ramereth** [comment]
!bump patch openstack_stein

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v10.2.1.  Have a nice day!

**Pull request merged**
